name: Build

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: windows-x86-64
            os: windows-latest
            publish-flags: >-
              /p:PublishProfile=Win-x64
              /p:GenerateAppxPackageOnBuild=true
              /p:AppxPackageSigningEnabled=true
              /p:PackageCertificateThumbprint="$WINDOWS_PFX_THUMBPRINT"
            artifacts: |-
              .\bin\Release\net7.0\publish\win-x64\*.exe
          #- os: macos-latest
          #- os: ubuntu-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 7.0.x
          cache: true

      - name: Restore dependencies
        run: dotnet.exe restore --locked-mode

      - name: Prepare certificate
        if: ${{ startsWith(matrix.name, "windows-") }}
        env:
          WINDOWS_PFX_FILE: ${{ secrets.WINDOWS_PFX_FILE }}
          WINDOWS_PFX_PASSWORD: ${{ secrets.WINDOWS_PFX_PASSWORD }}
        run: |
          echo "$WINDOWS_PFX_FILE" >cert.pfx.asc
          certutil -decode cert.pfx.asc cert.pfx
          certutil -user -q -p "$WINDOWS_PFX_PASSWORD" -importpfx cert.pfx NoRoot

      - name: Build
        env:
          WINDOWS_PFX_THUMBPRINT: ${{ secrets.WINDOWS_PFX_THUMBPRINT }}
        run: dotnet publish --no-restore /p:Configuration=Release ${{ matrix.publish-flags }}

      #- name: Test
      #  run: dotnet test --no-build --verbosity normal
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Launcher-win64.exe
          path: ${{ matrix.artifacts }}
