name: Build

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            publish-flags: >-
              /p:PublishProfile=Win64
            artifacts: |-
              .\bin\Release\net7.0\publish\win-x64\*.exe
          #- os: macos-latest
          #- os: ubuntu-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 7.0.x
          cache: true

      - name: Restore dependencies
        run: dotnet.exe restore --locked-mode

      - name: Build
        run: dotnet publish --no-restore /p:Configuration=Release ${{ matrix.publish-flags }}

      #- name: Test
      #  run: dotnet test --no-build --verbosity normal
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Launcher-win64.exe
          path: ${{ matrix.artifacts }}
