name: Build

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: windows-x86-64
            os: windows-latest
            publish-flags: >-
              /p:PublishProfile=Win-x64
              /p:GenerateAppxPackageOnBuild=true
              /p:AppxPackageSigningEnabled=true
              /p:PackageCertificateThumbprint="$WINDOWS_PFX_THUMBPRINT"
            artifacts: |-
              .\bin\Release\net7.0\publish\win-x64\*.exe
          #- os: macos-latest
          #- os: ubuntu-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 7.0.x
          cache: true

      - name: Restore dependencies
        run: dotnet.exe restore --locked-mode

      - name: Build
        env:
          WINDOWS_PFX_THUMBPRINT: ${{ secrets.WINDOWS_PFX_THUMBPRINT }}
        run: dotnet publish --no-restore /p:Configuration=Release ${{ matrix.publish-flags }}

      #- name: Test
      #  run: dotnet test --no-build --verbosity normal
      
      - name: Sign
        if: ${{ startsWith(matrix.name, 'windows-') }}
        uses: GabrielAcostaEngler/signtool-code-sign@main
        with:
          certificate: '${{ secrets.WINDOWS_PFX_FILE }}'
          cert-password: '${{ secrets.WINDOWS_PFX_PASSWORD }}'
          cert-sha1: '${{ secrets.WINDOWS_PFX_THUMBPRINT }}'
          cert-description: 'BrimWorld self-signed certificate'
          folder: '.\bin\Release\net7.0\publish\win-x64\'
          recursive: false

      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Launcher-win64.exe
          path: ${{ matrix.artifacts }}
